// src/app/layout.tsx
import "./globals.css"; 
import Notification from "./component/notification";
import { DarkModeProvider } from '@/contexts/DarkModeContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <DarkModeProvider>
          {children}
          <Notification.ToastContainer />
        </DarkModeProvider>
      </body>
    </html>
  )
}