import Dashboard from "../component/dashboard"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Dashboard>{children}</Dashboard>

    </html>
  )
}
